import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Providers from "./Providers";
import PostProvider from "@/context/PostProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <PostProvider>
          <Providers>
            <div className="flex min-h-screen">
              <Sidebar />

              <div className="flex flex-col flex-1">
                <Header />
                <main className="p-4">{children}</main>
              </div>
            </div>
          </Providers>
        </PostProvider>
      </body>
    </html>
  );
}
